services: # 이 항목 밑에 실행하려는 컨테이너들을 정의
  pharmacy-recommendation-redis:
    platform: linux/amd64
    container_name: pharmacy-recommendation-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    ports:
      - "6379:6379"
  pharmacy-recommendation-database:
    platform: linux/amd64
    container_name: pharmacy-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      - MARIADB_DATABASE=pharmacy-recommendation
      - MARIADB_ROOT_PASSWORD=1234
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)