spring:
  application:
    name: findpharmacy
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306:3306/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      port: 6379
      host: localhost
  jpa:
    hibernate:
      ddl-auto: validate
kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
      url:
        search-address: https://dapi.kakao.com/v2/local/search/keyword.json
